language: java

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew compileJava
  - ./gradlew compileTestJava
  - ./gradlew test
deploy:
  provider: heroku
  api_key: d6866b7b-bfd9-4a6a-aaff-595592f4122f
  app: backend-desapp
