language: kotlin
services:
- mysql
jdk:
- oraclejdk9
before_install:
- wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
- unzip gradle-6.6.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-6.6.1
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle wrapper
script:
- gradle check
deploy:
  provider: heroku
  api_key: d6866b7b-bfd9-4a6a-aaff-595592f4122f
  app: backend-desapp
